// 结衣 API 路由定义 - api client 会自动补 /api 前缀

export const JIEYI_API = {
  KNOWLEDGE: '/knowledge',
  KNOWLEDGE_SPLIT: (id: string) => `/knowledge/${id}/split`,
  SCHEDULE: '/schedule',
  SCHEDULE_SUGGEST: '/schedule/suggest',
  DAILY_PLAN: '/daily-plan',
  JIEYI_TODAY_AGGREGATE: (date?: string) => date ? `/jieyi/today/aggregate?date=${encodeURIComponent(date)}` : '/jieyi/today/aggregate',
  AGENT_JIEYI_TODAY: (date?: string) => date ? `/agent/jieyi/today?date=${encodeURIComponent(date)}` : '/agent/jieyi/today',
  DEEP_LEARNING_PREPARE: '/agent/jieyi/deep-learning/prepare',
  DEEP_LEARNING_ACCEPTANCE: '/agent/jieyi/deep-learning/acceptance',
  DEEP_LEARNING_SESSION: '/agent/jieyi/deep-learning/session',
  DEEP_LEARNING_SESSION_STEP: (sessionId: string) => `/agent/jieyi/deep-learning/session/${encodeURIComponent(sessionId)}/step`,
  TODAY: (date?: string) => date ? `/jieyi/today?date=${encodeURIComponent(date)}` : '/jieyi/today',
  THOUGHTS: '/jieyi/thoughts',
  DAILY_REVIEW: (date?: string) => date ? `/daily-review?date=${encodeURIComponent(date)}` : '/daily-review',
  AGENT_DAILY_CONTEXT: (date: string) => `/agent/jieyi/daily-context?date=${encodeURIComponent(date)}`,
  AGENT_WRITE_NEXT_PLAN: '/agent/jieyi/write-next-plan',
  ACTIVITIES: '/activities',
  ACTIVITY_FINISH: (id: string) => `/activities/${id}/finish`,
  MOOD: '/mood',
  WISDOM: '/wisdom',
  REALITY_ISSUES: '/jieyi/reality-issues',
  REALITY_ISSUE_FOCUS: '/jieyi/reality-issues/focus',
  REALITY_ISSUE: (issueId: number | string) => `/jieyi/reality-issues/${encodeURIComponent(issueId)}`,
  REALITY_ISSUE_SET_FOCUS: (issueId: number | string) => `/jieyi/reality-issues/${encodeURIComponent(issueId)}/focus`,
  REALITY_ISSUE_ENTRIES: (issueId: number | string) => `/jieyi/reality-issues/${encodeURIComponent(issueId)}/entries`,
  REALITY_ISSUE_ENTRY_CONFIRM: (issueId: number | string, entryId: number | string) => `/jieyi/reality-issues/${encodeURIComponent(issueId)}/entries/${encodeURIComponent(entryId)}/confirm`,
  REALITY_ISSUE_ENTRY_REJECT: (issueId: number | string, entryId: number | string) => `/jieyi/reality-issues/${encodeURIComponent(issueId)}/entries/${encodeURIComponent(entryId)}/reject`,
  REALITY_ISSUE_PRACTICES: (issueId: number | string) => `/jieyi/reality-issues/${encodeURIComponent(issueId)}/practices`,
  REALITY_ISSUE_PRACTICE_FEEDBACK: (issueId: number | string, scheduleId: number | string) => `/jieyi/reality-issues/${encodeURIComponent(issueId)}/practices/${encodeURIComponent(scheduleId)}/feedback`,
  REALITY_ISSUE_KNOWLEDGE_ANALYSIS: (issueId: number | string) => `/jieyi/reality-issues/${encodeURIComponent(issueId)}/knowledge-analysis`,
  REALITY_ISSUE_KNOWLEDGE_METHOD: (issueId: number | string) => `/jieyi/reality-issues/${encodeURIComponent(issueId)}/knowledge-analysis/method-candidate`,
  REALITY_ISSUE_PROMOTE_METHOD_VERSION: (issueId: number | string, entryId: number | string) => `/jieyi/reality-issues/${encodeURIComponent(issueId)}/entries/${encodeURIComponent(entryId)}/promote-method-version`,
} as const;
