"""结衣知行思道使用的稳定方法论种子。"""

JIEYI_METHOD_LIBRARY = [
    {
        "id": "sleep-judgment",
        "pillar": "身体",
        "practice": "早睡",
        "statement": "保护判断力，比多工作两小时重要。",
        "question": "你今天最应该保护的是睡眠，还是继续硬撑产出？",
        "reason": "睡眠是第二天判断力的本金。缺觉会让你更容易冲动、逃避、刷手机和做低质量决定。",
        "suggestion": "今晚先把睡前最后一个动作定清楚：到点关屏，留出明天的判断力。",
        "source": "wealth-habits · 纳瓦尔/致富习惯",
        "tags": ["身体", "判断力", "富人习惯"],
    },
    {
        "id": "review-compound",
        "pillar": "复利",
        "practice": "复盘",
        "statement": "经验只有被整理，才会产生复利。",
        "question": "今天哪件事如果不复盘，明天还会重复浪费你？",
        "reason": "复盘不是写日记，是把一次经历变成下次更快的判断。",
        "suggestion": "晚上只写三句：做到了什么、没做到什么、明天怎么改。",
        "source": "wealth-habits · 致富习惯/计划-记录-复盘",
        "tags": ["复盘", "复利", "方法论"],
    },
    {
        "id": "cashflow-visible",
        "pillar": "资产",
        "practice": "记账",
        "statement": "看见现金流，才有资格调整资产。",
        "question": "你今天有哪笔钱是不想面对、但必须看见的？",
        "reason": "不知道钱去哪，就不可能让钱为你工作。小额支出长期会变成资产缺口。",
        "suggestion": "今天只记录一笔最没必要的支出，不做复杂财务分析。",
        "source": "wealth-habits · 拿铁因素",
        "tags": ["资产", "现金流", "富人习惯"],
    },
    {
        "id": "leverage-work",
        "pillar": "作品",
        "practice": "高杠杆事",
        "statement": "每天做一件未来仍然产生收益的事。",
        "question": "你今天做的事，明天还会继续替你产生价值吗？",
        "reason": "富人不是只卖时间，而是持续累积作品、系统、资产和判断力。",
        "suggestion": "把高杠杆事压到 20 分钟：写一段可复用文档、沉淀一个模板、修一个长期卡点。",
        "source": "wealth-habits · Dan Koe/纳瓦尔",
        "tags": ["高杠杆", "作品", "资产"],
    },
    {
        "id": "focus-one-thing",
        "pillar": "判断力",
        "practice": "深度工作",
        "statement": "富人靠聚焦放大判断，不靠同时处理更多事。",
        "question": "今天哪一件事值得你关掉其他入口，认真做 45 分钟？",
        "reason": "多任务处理会制造忙碌感，但真正改变结果的是深度工作块。",
        "suggestion": "今天只安排一个无干扰深度块，开始前写下“这 45 分钟只做什么”。",
        "source": "wealth-habits · Dan Koe/致富习惯",
        "tags": ["专注", "深度工作", "判断力"],
    },
    {
        "id": "stop-doing",
        "pillar": "边界",
        "practice": "不做清单",
        "statement": "知道不做什么，比知道做什么更保护命运。",
        "question": "今天哪件事看起来有用，其实在偷走你的主线？",
        "reason": "方向错时，越努力越远。Stop Doing List 是给注意力设边界。",
        "suggestion": "早上写一条今天不做什么；晚上检查有没有被它拖走。",
        "source": "wealth-habits · 段永平",
        "tags": ["边界", "本分", "长期主义"],
    },
    {
        "id": "desire-management",
        "pillar": "欲望",
        "practice": "少刷短视频",
        "statement": "被感官绑架，是变废最快的方式。",
        "question": "你现在刷的是身体真正需要，还是外界喂给你的欲望？",
        "reason": "高刺激会抬高多巴胺阈值，让真实生活和长期积累显得无聊。",
        "suggestion": "想刷时先停 30 秒，问“这是腹的需求，还是目的欲望”。",
        "source": "wealth-habits · 为腹不为目",
        "tags": ["欲望", "多巴胺", "道德经"],
    },
    {
        "id": "meditation-attention",
        "pillar": "注意力",
        "practice": "冥想",
        "statement": "冥想不是放空，是训练注意力回到当下。",
        "question": "今天你的注意力最容易被什么带走？",
        "reason": "注意力是所有判断和行动的入口。无法把心收回来，就很难把行动落下去。",
        "suggestion": "做 5 分钟腹式呼吸；走神时只标记“走神了”，然后回到呼吸。",
        "source": "meditation-practice · 女娲蒸馏",
        "tags": ["冥想", "注意力", "恢复"],
    },
]
